language: c
sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc
      before_install:
        - sudo apt-get install gfortran
    - os: linux
      compiler: gcc
      before_install:
        - sudo apt-get install gfortran
        - sudo apt-get install mpich
    - os: linux
      compiler: gcc
      before_install:
        - sudo apt-get install gfortran
        - sudo apt-get install openmpi-bin openmpi-doc libopenmpi-dev
    - os: osx
      compiler: gcc
      before_install:
        - brew update > /dev/null
        - brew install gcc > /dev/null
        - export FC=gfortran
    - os: windows
      compiler: gcc
      before_install:
           # remove the sh.exe file, which prevents MinGW from working
         - where sh > sh_loc.txt
         - powershell -command "cat sh_loc.txt | rm"
         - echo $MDI_CONFIG_OPTIONS
      install:
         # Make Python package build
         - mkdir python_build
         - cd python_build
         - cmake -G "MinGW Makefiles" -Dpython_package=ON ..
         - mingw32-make VERBOSE=1
         - mingw32-make install
         - cd ..
         # Make local install build
         - mkdir build
         - cd build
         - cmake -G "MinGW Makefiles" -DCMAKE_INSTALL_PREFIX=./install ..
         - mingw32-make VERBOSE=1
         - ls
         - mingw32-make install
         - ls
         - ls MDI_Library
         - curl -L -o test_codes.tar.gz https://github.com/MolSSI/MDI_Test_Codes/archive/v0.1.1.tar.gz
         - tar xvzf test_codes.tar.gz
         - cd MDI_Test_Codes-0.1.1
         - mkdir build
         - cd build
         - ls ~/build/MolSSI/MDI_Library/build/install/include/MDI_Library
         - ls ~/build/MolSSI/MDI_Library/build/install/lib/MDI_Library
         - cmake -Dmdi_include_path=~/build/MolSSI/MDI_Library/build/install/include/MDI_Library -Dmdi_lib_path=~/build/MolSSI/MDI_Library/build/install/lib/MDI_Library -G "MinGW Makefiles" ..
         - mingw32-make
         - ls
      script:
         - ls
         - export PATH=$PATH:~/build/MolSSI/MDI_Library/build/install/lib/MDI_Library
         - export PATH=$PATH:~/build/MolSSI/MDI_Library/build/install/include/MDI_Library
         
         # Fortran executables don't seem to search the $PATH variable
         - cp ~/build/MolSSI/MDI_Library/build/install/lib/MDI_Library/*.dll* .
         - ls MDI_Test_Codes/STUBS_MPI
         - cp MDI_Test_Codes/STUBS_MPI/*.dll* .
         - ls

         # Confirm that all executables have been created
         - find driver_cxx.exe engine_cxx.exe driver_f90.exe engine_f90.exe driver_py.py engine_py.py

         # Run a CXX-CXX test calculation using TCP/IP
         - ../../../tests/cxx-cxx_tcp.sh

         # Run a CXX-Fortran test calculation using TCP/IP
         - ../../../tests/cxx-f90_tcp.sh

         # Run a CXX-Python test calculation using TCP/IP
         - ../../../tests/cxx-py_tcp.sh

         # Run a Fortran-CXX test calculation using TCP/IP
         - ../../../tests/f90-cxx_tcp.sh

         # Run a Fortran-Fortran test calculation using TCP/IP 
         - ../../../tests/f90-f90_tcp.sh

         # Run a Fortran-Python test calculation using TCP/IP
         - ../../../tests/f90-py_tcp.sh

         # Run a Python-CXX test calculation using TCP/IP
         - ../../../tests/py-cxx_tcp.sh

         # Run a Python-Fortran test calculation using TCP/IP
         - ../../../tests/py-f90_tcp.sh

         # Run a Python-Python test calculation using TCP/IP
         - ../../../tests/py-py_tcp.sh


install:
  # Make Python package build
  - mkdir python_build
  - cd python_build
  - cmake -Dpython_package=ON ..
  - make
  - sudo make install
  - cd ..

  # Make local install build
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=./install ..
  - make
  - make install
  - ls
  - ls MDI_Library

  # Build test codes
  - curl -L -o test_codes.tar.gz https://github.com/MolSSI/MDI_Test_Codes/archive/v0.1.1.tar.gz
  - tar xvzf test_codes.tar.gz
  - cd MDI_Test_Codes-0.1.1
  - mkdir build
  - cd build
  - ls ~/build/MolSSI/MDI_Library/build/install/include/MDI_Library
  - ls ~/build/MolSSI/MDI_Library/build/install/lib/MDI_Library
  - cmake -Dmdi_include_path=~/build/MolSSI/MDI_Library/build/install/include/MDI_Library -Dmdi_lib_path=~/build/MolSSI/MDI_Library/build/install/lib/MDI_Library ..
  - make
  - ls

script:
  - ls
  # Confirm that all executables have been created
  - find driver_cxx engine_cxx driver_f90 engine_f90 driver_py.py engine_py.py

  # Run a CXX-CXX test calculation using TCP/IP
  - ../../../tests/cxx-cxx_tcp.sh

  # Run a CXX-Fortran test calculation using TCP/IP
  #- ../../../tests/cxx-f90_tcp.sh

  # Run a CXX-Python test calculation using TCP/IP
  - ../../../tests/cxx-py_tcp.sh

  # Run a Fortran-CXX test calculation using TCP/IP
  #- ../../../tests/f90-cxx_tcp.sh

  # Run a Fortran-Fortran test calculation using TCP/IP 
  #- ../../../tests/f90-f90_tcp.sh

  # Run a Fortran-Python test calculation using TCP/IP
  #- ../../../tests/f90-py_tcp.sh

  # Run a Python-CXX test calculation using TCP/IP
  - ../../../tests/py-cxx_tcp.sh

  # Run a Python-Fortran test calculation using TCP/IP
  #- ../../../tests/py-f90_tcp.sh

  # Run a Python-Python test calculation using TCP/IP
  - ../../../tests/py-py_tcp.sh
